version: '2'
services:
  bkdb:
    image: mongo
    hostname: db
    restart: always

  bktelegram:
    hostname: bktelegram
    restart: always
    build: .
    environment:
      - "API_TOKEN=TOKEN"
      - PYTHONUNBUFFERED=0
    links:
      - bkdb
    ports:
      - "4000:4000"
